name: proyectemos
description: A new Flutter project.

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dependency_validator: ^5.0.2

  # Firebase
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  firebase_storage: ^13.0.2
  firebase_app_check: ^0.4.1

  jumping_dot: ^0.0.6

  # Authentication
  google_sign_in: ^7.2.0

  # Google icon
  font_awesome_flutter: ^10.1.0

  # State management
  provider: ^6.1.1
  path_provider: ^2.0.11

  # Video
  youtube_player_flutter: ^9.0.1
  appinio_video_player: ^1.2.2
  video_player: ^2.7.0
  chewie: ^1.7.0

  #Seguranca
  flutter_dotenv: ^6.0.0

  # url
  url_launcher: ^6.3.2

  # ImagePicker
  image_picker: ^1.0.0
  image: ^4.0.17

  # Smooth page indicator
  smooth_page_indicator: ^1.0.0+2

  # Splash
  flutter_native_splash: ^2.4.0

  # Launcher icon
  flutter_launcher_icons: ^0.14.4

  file_picker: ^9.0.0

  # Email
  googleapis: ^13.0.0
  googleapis_auth: ^1.6.0

  carousel_slider: ^5.0.0

  # Permissions
  permission_handler: ^12.0.1

  # Audio
  simple_ripple_animation: ^0.1.0
  just_audio: ^0.10.5
  percent_indicator: ^4.2.2
  audioplayers: ^6.5.1

  # Toast
  toast: ^0.3.0

  # Data
  shared_preferences: ^2.0.15

  # Internacional
  intl: ^0.20.2

  # Email
  flutter_mailer: ^3.0.1
  mailer: ^6.5.0
  archive: ^4.0.7

  # Card
  card_swiper: ^3.0.1

  # Dropdown
  dropdown_button2: ^2.3.9

  # Responsividade
  flutter_screenutil: ^5.7.0

  #Record
  flutter_sound: ^9.28.0
#  record: ^5.1.2

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/splash.png"

  android_12:
    image: "assets/images/splash.png"
    color: "#ffffff"
    icon_background_color: "#111111"

flutter_launcher_icons:
  image_path: "assets/images/splash.png"
  android: "launcher_icon"
  min_sdk_android: 21
  adaptative_icon_background: "#ffffff"
  adaptative_icon_foreground: "assets/images/icon-android.png"
  lints: ^2.1.1

dev_dependencies:

  flutter_test:
    sdk: flutter
  mockito:
  build_runner:
  lints: ^6.0.0

  #Lint
  flutterando_analysis: ^0.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/audios/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 400
